### ISSUE TITLE
Problema en POS ...Cliente Varios 

### ISSUE THREAD

**Issue by antoniogalli** [ShinSeiki/technik_odoo_instance#10]
El problema es cuando se vende menor a 700 soles no es obligatorio tener un cliente se puede usar el cliente varios que enviar un RUC "00000000000" o un DNI "00000000"  en el xml  

Revisar el manual del programador  https://cpe.sunat.gob.pe/sites/default/files/inline-files/manual_programador.pdf
Consultar https://cpe.sunat.gob.pe/node/122

En la gestión de ventas POS de Viniteca no presenta el problema 

Revisa por favor que todas las versiones estén corregidas y no presente la validación

**Comment by ShinSeiki** [comment]
obsevacion funciona completamente en viniteka

**Comment by antoniogalli** [comment]
establecer en la configuración del cliente como tipo: **Non-Domiciled Tax Document**
