### ISSUE TITLE
Cotizar Subir Addom Producto Kamba ficha en transparencia. "mi_addon_producto"

### ISSUE THREAD

**Issue by antoniogalli** [ShinSeiki/technik_odoo_instance#19]
Detalle visual para la vista kamba de productos. Por favor subir el addon "mi_addon_producto" 

[mi_addon_producto.zip](https://github.com/user-attachments/files/16981059/mi_addon_producto.zip)

**Comment by ShinSeiki** [comment]
prioridad para subir en APROMED, luego al resto

**Comment by antoniogalli** [comment]
Opacidad al 70 del color blanco
![opacidad](https://github.com/user-attachments/assets/ea937dde-d7b4-4498-b346-9c17a6efc946)
